bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=postgres password=qwerty dbname=restapi_dev sslmode=disable"
session_key = "dlfkjasldfjskfjdsjflajefljlksjfklsjflkjaselfjlajfkljselkfjlkasjljflkejlfjaslkjfl"
